on: [push]

jobs:
  kubeflow_upload_job:
    runs-on: ubuntu-latest
    name: Kubeflow Upload and Run Pipeline
    steps:
    - name: Checkout task
      uses: actions/checkout@master
    #- run: npm install
    - name: Kubeflow Upload and Run Step
      id: upload-run
      uses: marts2007/kubeflow-pipeline-github-action@master
      with:
        kubeflowEndpoint: '${{ secrets.ENDPOINTURL }}'
        pipelineFilePath: '${{ inputs.pipelineFilePath }}'
        maxFileSizeBytes: '${{ inputs.maxFileSizeBytes }}'
        pipelineName: 'testPL-${{ github.run_number }}'
        pipelineParams: '${{ inputs.pipelineParams }}'
        experimentName: '${{ inputs.experimentName }}'
        namespace: '${{ inputs.namespace }}'
        runDescription: '${{ inputs.runDescription }}'
        runName: '${{ inputs.runName }}'
        userid: '${{ secrets.USERID }}'
        password: '${{ secrets.PASSWORD }}'

    # Use the outputs from the `Kubeflow Upload and Run Step`
    - name: Get all outputs
      run: |
        echo "Pipeline version id ${{ steps.upload-run.outputs.kf_pipeline_version_id }}"
        echo "Pipeline id ${{ steps.upload-run.outputs.kf_pipeline_id }}"
        echo "Experiment id ${{ steps.upload-run.outputs.kf_experiment_id }}"
        echo "Run id ${{ steps.upload-run.outputs.kf_run_id }}"
