on: [push]
inputs:
  pipelineFilePath:
    description: 'File path of the pipeline file to be uploaded. Must be a compressed .tar.gz file, no larger than 32MB.'
    required: true
    default: 'action/code/tests/pipeline2.tar.gz'
  maxFileSizeBytes:
    description: 'max pipeline file size'
    required: true
    default: 32000000
  pipelineName:
    description: 'Pipeline name for new upload.'
    required: true
    default: ''  
  pipelineParams:
    description: ''
    required: false
    default: ''
  experimentName:
    description: 'Name a new experiment, or choose an existing experiment name.'
    required: true
    default: 'test'
  namespace:
    description: 'project kubeflow namespace'
    required: true
    default: 'inv4mat'
  runDescription:
    description: ''
    required: true
    default: ''
  runName:
    description: 'The name of the new run.'
    required: true
    default: 'testRUN'





jobs:
  kubeflow_upload_job:
    runs-on: ubuntu-latest
    name: Kubeflow Upload and Run Pipeline
    steps:
    - name: Checkout task
      uses: actions/checkout@master
    - run: npm install
    - name: Kubeflow Upload and Run Step
      id: upload-run
      uses: marts2007/kubeflow-pipeline-github-action@master
      with:
        kubeflowEndpoint: '${{ secrets.KUBEFLOWENDPOINT }}'
        pipelineFilePath: '${{ inputs.pipelineFilePath.default }}'
        maxFileSizeBytes: '${{ inputs.maxFileSizeBytes.default }}'
        pipelineName: 'testPL-${{ github.run_number }}'
        pipelineParams: '${{ inputs.pipelineParams }}'
        experimentName: '${{ inputs.experimentName }}'
        namespace: '${{ inputs.namespace }}'
        runDescription: '${{ inputs.runDescription }}'
        runName: '${{ inputs.runName }}'
        userid: '${{ secrets.USERID }}'
        password: '${{ secrets.PASSWORD }}'

    # Use the outputs from the `Kubeflow Upload and Run Step`
    - name: Get all outputs
      run: |
        echo "Pipeline version id ${{ steps.upload-run.outputs.kf_pipeline_version_id }}"
        echo "Pipeline id ${{ steps.upload-run.outputs.kf_pipeline_id }}"
        echo "Experiment id ${{ steps.upload-run.outputs.kf_experiment_id }}"
        echo "Run id ${{ steps.upload-run.outputs.kf_run_id }}"
